# Generated by Django 4.2.17 on 2024-12-23 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefeeditem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilefeeditem',
            options={'ordering': ['-created_on']},
        ),
    ]
